### ISSUE TITLE
Gerar versões em PDF dos volumes

### ISSUE THREAD

**Issue by bcdavasconcelos** [LeoGilsonRibeiro/leogilsonribeiro.github.io#1]
## Elementos

*Obs: Isso vai me ajudar a decidir qual método utilizar, mas talvez esbarremos em alguma limitação no caminho.*

Seria desejável que o(s) pdf(s) contivessem... (deixar marcadas as opções que se aplicam)

- [x] Um volume (fazer no formato de uma coleção, com 9 volumes em 9 arquivos em PDF).
- [x] Sumário
- [x] Sumário com links para os textos.
- [x] Capa
- [x] Contracapa
- [ ] Cólofon
- [ ] Epígrafe (qual)
- [ ] Dedicatória
- [x] Começar cada capítulo (H2) em uma nova página
- [ ] Inserir página em branco entre seções (H1).
- [ ] Algum outro elemento ou característica específica, (@ferey99)?

## Método

Passos:

- [x] Pesquisar maneira de gerar os pdfs usando o [mkdocs](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#pdf--site-conversion) e os passos.

Se não for possível fazer utilizando MkDocs:
- [x] Pesquisar modelos adequados.
- [x] Preparar template e conferir se o Fernando (@ferey99) está de acordo.

**Comment by ferey99** [comment]
Oi Bernardo,
Aos poucos vamos ver como e se será possível organizar os volumes em PDF. 
Um abraço,
Fernando
    Em quinta-feira, 26 de janeiro de 2023 15:16:58 BRT, Bernardo C.D.A. Vasconcelos ***@***.***> escreveu:  
 
 


Elementos

Obs: Isso vai me ajudar a decidir qual método utilizar, mas talvez esbarremos em uma limitação no caminho.

Seria desejável que o(s) pdf(s) contivessem...
   
   -  Um volume (fazer no formato de uma coleção, com 9 volumes em 9 arquivos em PDF).
   -  Sumário
   -  Sumário com links para os textos.
   -  Capa
   -  Contracapa
   -  Cólofon
   -  Epígrafe (qual)
   -  Dedicatória
   -  Começar cada capítulo (H2) em uma nova página
   -  Inserir página em branco entre seções (H1).
   -  Algum outro elemento ou característica específica, ***@***.***)?

Método

Passos:
   
   -  Pesquisar maneira de gerar os pdfs usando o mkdocs e os passos.

Se não for possível fazer utilizando MkDocs:
   
   -  Pesquisar modelos adequados.
   -  Preparar template e conferir se o Fernando ***@***.***) está de acordo.
